export enum UserRole {
  ISP_OWNER = 'ISP_OWNER',
  ISP_ADMIN = 'ISP_ADMIN',
  BILLING = 'BILLING',
  SUPPORT = 'SUPPORT',
  TECHNICIAN = 'TECHNICIAN',
  READ_ONLY = 'READ_ONLY',
}

export enum CustomerStatus {
  LEAD = 'LEAD',
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  EXPIRED = 'EXPIRED',
  TERMINATED = 'TERMINATED',
}

export enum SubscriptionStatus {
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  GRACE = 'GRACE',
  SUSPENDED = 'SUSPENDED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
}

export enum InvoiceStatus {
  DRAFT = 'DRAFT',
  ISSUED = 'ISSUED',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
  PAID = 'PAID',
  OVERDUE = 'OVERDUE',
  CANCELLED = 'CANCELLED',
}

export enum PaymentMethod {
  CASH = 'CASH',
  UPI = 'UPI',
  BANK_TRANSFER = 'BANK_TRANSFER',
  ONLINE_GATEWAY = 'ONLINE_GATEWAY',
  CHEQUE = 'CHEQUE',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
}

export enum RouterStatus {
  ONLINE = 'ONLINE',
  OFFLINE = 'OFFLINE',
  UNREACHABLE = 'UNREACHABLE',
  ERROR = 'ERROR',
  CONFIGURING = 'CONFIGURING',
  CONNECTED = 'CONNECTED',
  API_AUTH_FAILED = 'API_AUTH_FAILED',
  VPN_UNREACHABLE = 'VPN_UNREACHABLE',
  UNSUPPORTED_ROUTEROS = 'UNSUPPORTED_ROUTEROS',
  DEGRADED = 'DEGRADED',
}

export enum RouterConnectionMethod {
  DIRECT_API = 'DIRECT_API',
  SSTP_TUNNEL = 'SSTP_TUNNEL',
}

export enum RouterApiMethod {
  AUTO = 'AUTO',
  REST_API = 'REST_API',
  BINARY_API = 'BINARY_API',
}

export enum PlanStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum BillingCycle {
  MONTHLY = 'MONTHLY',
  QUARTERLY = 'QUARTERLY',
  HALF_YEARLY = 'HALF_YEARLY',
  ANNUAL = 'ANNUAL',
  CUSTOM = 'CUSTOM',
}

export enum SpeedUnit {
  MBPS = 'MBPS',
  KBPS = 'KBPS',
  GBPS = 'GBPS',
}

export enum AuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  STATUS_CHANGE = 'STATUS_CHANGE',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  SUSPEND_SUBSCRIBER = 'SUSPEND_SUBSCRIBER',
  REACTIVATE_SUBSCRIBER = 'REACTIVATE_SUBSCRIBER',
  COA_DISCONNECT = 'COA_DISCONNECT',
  COLLECT_PAYMENT = 'COLLECT_PAYMENT',
  GENERATE_INVOICE = 'GENERATE_INVOICE',
}

export enum TicketStatus {
  OPEN = 'OPEN',
  ASSIGNED = 'ASSIGNED',
  IN_PROGRESS = 'IN_PROGRESS',
  WAITING_CUSTOMER = 'WAITING_CUSTOMER',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
}

export enum TicketPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}
